name = "url-shortener"
compatibility_date = "2024-07-12"
pages_build_output_dir = "dist"

[functions]
"directory" = "./functions"

[vars]
TURNSTILE_SECRET = "${TURNSTILE_SECRET}"

[[kv_namespaces]]
binding = "URLS"
id = "${KV_URLS_ID}"