name = "url-to"
main = "packages/worker/src/index.ts"
compatibility_date = "2024-07-12"

[custom_domains]
url_to_kawin_dev = "url-to.kawin.dev"

[[kv_namespaces]]
binding = "URLS"
id = "d4483eee51484f8587013ec77aabcfe5"
preview_id = "local_kv_for_dev"