name = "url-shortener"
main = "functions/_worker.ts"
compatibility_date = "2024-07-12"
pages_build_output_dir = "dist"

[vars]
TURNSTILE_SECRET = "${TURNSTILE_SECRET}"

[[kv_namespaces]]
binding = "URLS"
id = "${KV_URLS_ID}"